[package]
name = "libnexus"
version = "0.1.0"
edition = "2021"
license = "LGPL-3.0"

[dependencies]
bytes = "1.8.0"
chrono = "0.4.38"
serde = "1.0.215"
tokio.workspace = true
tracing = "0.1.40"
uuid = { version = "1.11.0", features = ["v4"] }
