[package]
name = "smb3-server"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"

[dependencies]
libnexus = { path = "../libnexus" }
tokio.workspace = true
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
